<?php
/**
 * @file
 * Code for Sign_in_module.
 */

 
/**
 *  Implements hook_menu().
 */
function sign_in_module_menu() {
	$items = array();
	$items['sign-in-page'] = array(
	  'title' => 'SignIn',
	  'page callback' => 'drupal_get_form',
	  'page arguments' => array('sign_in_page_form'),
	  'access callback' => TRUE,
	  );
	  return $items;
}

/**
 * Build sign in form
 */
function sign_in_page_form($form, $form_state) {
	$form = array();
	$form['name'] = array(
     '#type' => 'textfield',
     '#title' => t('Name'),
     '#size' => 20,
	 '#maxlength' => 12,
    );
    $form['surname'] = array(
     '#type' => 'textfield',
     '#title' => t('Surname'),
     '#size' => 20,
	 '#maxlength' => 15,
    );
	$form['email'] = array(
	 '#type' => 'textfield',
	 '#title' => t('Email'),
	 '#size' => 20,
	 '#maxlength' => 16,
	);
    $form['phone'] = array(
	  '#type' => 'textfield',
	  '#title' => t('Number'),
	  '#size' => 20,
	  '#maxlength' => 16,
	 );
	$form['sign'] = array(
      '#type' => 'submit',
      '#value' => t('SignIn'),
	  '#submit' => array('insert_into_table'),
    );
	return $form;
}

/**
 * Validate function for sign_in_page_form.
 */

function sign_in_page_form_validate($form, &$form_state) {
 if(!is_numeric($form_state['values']['phone'])) {
	form_set_error('phone', t('Value in field "Phone" is incorrect.'));
 }

}





