<?php
/**
 * @file
 * Code for Sign_in_module.
 */

/**
 * Implementation of hook_permission().
*/
function users_db_permission() {
  return array(
    'db access' => array(
        'title' => t('Access Users Database'),
        'description' => t('Allows an admin to access database'),
        )
	);
}
 
/**
 *  Implements hook_menu().
 */
function sign_in_module_menu() {
  $items = array();
  $items['sign-in-page'] = array(
    'title' => 'Sign In',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sign_in_page_form'),
    'access callback' => TRUE,
    );
  $items['users-db'] = array(
    'title' => 'Users database',
    'page callback' => 'show_users_db',
    'access arguments' => array('db access'),
    );
  return $items;
}

/**
 *  Creates sign in form
 */
function sign_in_page_form($form, $form_state) {
  $form = array();
  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#required' => TRUE,
    '#size' => 20,
    '#maxlength' => 30,
  );
  $form['surname'] = array(
    '#type' => 'textfield',
    '#title' => t('Surname'),
    '#required' => TRUE,
    '#size' => 20,
    '#maxlength' => 30,
  );
  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => t('Email'),
    '#required' => TRUE,
    '#size' => 20,
    '#maxlength' => 50,
  );
  $form['phone'] = array(
    '#type' => 'textfield',
    '#title' => t('Number'),
    '#required' => TRUE,
    '#size' => 20,
    '#maxlength' => 16,
  );
  $form['sign'] = array(
    '#type' => 'submit',
    '#value' => t('SignIn'),
    '#submit' => array('sign_in_page_submit'),
  );
  return $form;
}

/**
 *  Selects all data from 'sign_in_users' table
*/
function show_users_db() {
  $users = '';
  //Query selects all data from 'sign_in_users' table
  $query = db_select('sign_in_users','n');
  $query -> fields('n', array(
            'name',
            'surname',
            'email',
            'phone'));
  //Shows 10 results per page
  $query = $query->extend('PagerDefault')->limit(10);
  $get_users_result = $query->execute()->fetchAll();
  //Shows query results one by one
  foreach($get_users_result as $record) {
    $users .= '<tr><td>' .$record->name. '</td>'.
        '<td>'. $record->surname. '</td>'.
        '<td>'. $record->email. '</td>'.
        '<td>'. $record->phone. '</td></tr>'; 		
  }
  //Shows text message if query returned 0 results
  if(empty($get_users_result)) {
    $users = "Sorry, there are no users in 'sign_in_users' table";
  }
  return '<table>'.
         '<tr>'.
         '<td><b>Name</b></td>'.
         '<td><b>Surname</b></td>'.
         '<td><b>Email</b></td>'.
         '<td><b>Phone</b></td>'.
         '</tr>'.
         $users. '</table>'.
	     theme('pager');
}

/**
 * Validate function for sign_in_page_form.
 */
function sign_in_page_form_validate($form, &$form_state){ 
  if(!preg_match('/^[a-zA-Z]{1,30}$/s',$form_state['values']['name'])){
    form_set_error('name',t("Name used in Your Name's field is not valid."));
  }
  if(!preg_match('/^[a-zA-Z]{1,30}$/s',$form_state['values']['surname'])){
    form_set_error('surname',t("Surname used in Your Surname's field is not valid."));
  }
  if (!valid_email_address($form_state['values']['email'])) {
    form_set_error('email', t("The email used in Your Email's field is not valid."));
  } 
  if(!preg_match('/^(\+?\d+)?\s*(\(\d+\))?[\s-]*([\d-]*)$/s',$form_state['values']['phone'])){
    form_set_error('phone', t("The phone used in Your Phone's field is not valid."));
  } 
}

/**
 *  Inserts data from $form form into 'sign_in_users' table
 */
function sign_in_page_submit($form, &$form_state)  {

  //Query inserts data into 'sign_in_users' table
  $insert = db_insert('sign_in_users')
    ->fields(array(
	  'name'    => $form_state['values']['name'],
 	  'surname' => $form_state['values']['surname'], 
	  'email'   => $form_state['values']['email'],
	  'phone'   => $form_state['values']['phone']))
    ->execute();
  if ($query > 0) {
    drupal_set_message(t("Data has been successfully added."));
  }
  else {
    drupal_set_message(t("Data hasn't been added."), 'error');
  }
}