<?php
/**
 * @file
 * Code for Sign_in_module.
 */

 
/**
 *  Implements hook_menu().
 */
function sign_in_module_menu() {
    $items = array();
    $items['sign-in-page'] = array(
	  'title' => 'SignIn',
	  'page callback' => 'drupal_get_form',
	  'page arguments' => array('sign_in_page_form'),
	  'access callback' => TRUE,
	  );
	 return $items;
}

/**
 *  Creating sign in form
 */
function sign_in_page_form($form, $form_state) {
	$form = array();
	$form['name'] = array(
     '#type' => 'textfield',
     '#title' => t('Name'),
     '#size' => 20,
	 '#maxlength' => 12,
    );
    $form['surname'] = array(
     '#type' => 'textfield',
     '#title' => t('Surname'),
     '#size' => 20,
	 '#maxlength' => 15,
    );
	$form['email'] = array(
	 '#type' => 'textfield',
	 '#title' => t('Email'),
	 '#size' => 20,
	 '#maxlength' => 16,
	);
    $form['phone'] = array(
	  '#type' => 'textfield',
	  '#title' => t('Number'),
	  '#size' => 20,
	  '#maxlength' => 16,
	 );
	$form['sign'] = array(
      '#type' => 'submit',
      '#value' => t('SignIn'),
	  '#submit' => array('sign_in_page_submit'),
    );
	return $form;
}

/**
 * Validate function for sign_in_page_form.
 */
function sign_in_page_form_validate($form, &$form_state) {
    if(!is_numeric($form_state['values']['phone'])) {
	   form_set_error('phone', t('Value in field "Phone" is incorrect.'));
    }
}

/**
 *  Inserting data from $form form into 'sign_in_users' table
 */
function sign_in_page_submit($form, &$form_state)  {

    //Variables that store data from form $form
    $name    = $form_state['values']['name'];
    $surname = $form_state['values']['surname'];
    $email   = $form_state['values']['email'];
    $phone   = $form_state['values']['phone'];
 
    //Query inserting data into 'sign_in_users' table
    $insert = db_insert('sign_in_users')
		->fields(array('name' => $name, 'surname' => $surname, 'email' => $email, 'phone' => $phone))
		->execute();
    drupal_set_message(t('Succesful'));
}





